const K='redditRadar.v1', PREF='redditRadar.preferences.v1', TCACHE='redditRadar.translationCache.v1';
const W={pain:.25,willingness:.20,frequency:.15,distribution:.10,mvp:.10,gap:.10,fit:.10};
const I18N={
  tr:{edition:'ATPS / FIRSAT MASASI — 01',title:'Reddit Fırsat Radarı',titleLine:'Fırsat Radarı',subtitle:'İnsanların gerçekten dert ettiği problemleri bul, sinyalleri topla, fikre dönüştür.',liveSource:'CANLI KAYNAK',refresh:'Akışı yenile ↻',export:'Dışa aktar',import:'İçe aktar',newIdea:'Yeni fikir +',navLive:'01 / Canlı akış',navDashboard:'02 / Özet',navIdeas:'03 / Fikir havuzu',navReview:'05 / Kontrol',search:'ARAMA',searchPlaceholder:'problem, ürün, müşteri, subreddit...',category:'KATEGORİ',status:'DURUM',all:'Tümü',ideaRecord:'FİKİR KAYDI',idea:'Fikir',problemSignal:'Problem / sinyal',customer:'Hedef müşteri',categoryTitle:'Kategori',sourceUrl:'Kaynak URL',statusTitle:'Durum',checkInterval:'Kontrol aralığı',scoring:'PUANLAMA / 1–5',save:'Kaydet →',totalIdeas:'Toplam fikir',strongIdeas:'85+ fırsat',reviewWaiting:'Kontrol bekliyor',liveSignals:'Canlı sinyal',scanning:'REDDIT / kaynaklar taranıyor…',updating:'Akış güncelleniyor.',liveError:'CANLI VERİ HATASI',sourceOffline:'Canlı kaynak şu anda cevap vermiyor.',lastScan:'SON TARAMA',subreddits:'SUBREDDIT',sourceErrors:'KAYNAK HATASI',preparing:'CANLI REDDIT SİNYALLERİ HAZIRLANIYOR…',noSignal:'Henüz canlı sinyal yok.',noDescription:'Açıklama yok',anonymous:'anonim',redditSource:'Reddit kaynağı ↗',promote:'Fikir havuzuna al →',signal:'SİNYAL / 100',noIdeas:'Bu görünümde fikir bulunamadı.',personalIdea:'KİŞİSEL FİKİR',reviewDue:'KONTROL ZAMANI',source:'Kaynak ↗',edit:'Aç / düzenle →',opportunity:'FIRSAT / 100',invalidJson:'Geçerli JSON seç.',pain:'Acı',willingness:'Ödeme isteği',frequency:'Tekrar',distribution:'Dağıtım',mvp:'MVP kolaylığı',gap:'Rekabet boşluğu',fit:'Uyum',translating:'İngilizce Reddit içerikleri Türkçeye çevriliyor…',translated:'Türkçe çeviri',original:'Orijinal',translationUnavailable:'Tarayıcı çevirisi desteklenmiyor; kaynak metin gösteriliyor.',statuses:{'İncele':'İncele','İzle':'İzle','Öncelikli':'Öncelikli','MVP':'MVP','Arşiv':'Arşiv'}},
  en:{edition:'ATPS / OPPORTUNITY DESK — 01',title:'Reddit Opportunity Radar',titleLine:'Opportunity Radar',subtitle:'Find problems people genuinely care about, collect the signals, and turn them into product ideas.',liveSource:'LIVE SOURCE',refresh:'Refresh feed ↻',export:'Export',import:'Import',newIdea:'New idea +',navLive:'01 / Live feed',navDashboard:'02 / Overview',navIdeas:'03 / Idea pool',navReview:'05 / Review',search:'SEARCH',searchPlaceholder:'problem, product, customer, subreddit...',category:'CATEGORY',status:'STATUS',all:'All',ideaRecord:'IDEA RECORD',idea:'Idea',problemSignal:'Problem / signal',customer:'Target customer',categoryTitle:'Category',sourceUrl:'Source URL',statusTitle:'Status',checkInterval:'Review interval',scoring:'SCORING / 1–5',save:'Save →',totalIdeas:'Total ideas',strongIdeas:'85+ opportunities',reviewWaiting:'Due for review',liveSignals:'Live signals',scanning:'REDDIT / scanning sources…',updating:'Updating feed.',liveError:'LIVE DATA ERROR',sourceOffline:'The live source is not responding right now.',lastScan:'LAST SCAN',subreddits:'SUBREDDITS',sourceErrors:'SOURCE ERRORS',preparing:'PREPARING LIVE REDDIT SIGNALS…',noSignal:'No live signals yet.',noDescription:'No description',anonymous:'anonymous',redditSource:'Open on Reddit ↗',promote:'Add to idea pool →',signal:'SIGNAL / 100',noIdeas:'No ideas in this view.',personalIdea:'PERSONAL IDEA',reviewDue:'REVIEW DUE',source:'Source ↗',edit:'Open / edit →',opportunity:'OPPORTUNITY / 100',invalidJson:'Choose a valid JSON file.',pain:'Pain',willingness:'Willingness to pay',frequency:'Frequency',distribution:'Distribution',mvp:'MVP ease',gap:'Market gap',fit:'Fit',translating:'Translating Reddit content…',translated:'Translated',original:'Original',translationUnavailable:'Browser translation is unavailable; showing source text.',statuses:{'İncele':'Review','İzle':'Watch','Öncelikli':'Priority','MVP':'MVP','Arşiv':'Archive'}}
};
const SEED_I18N={
R031:{tr:{idea:'AI Ajanları için DevSecOps Kural Paketi',problem:'AI kodlama ajanları proje güvenlik kurallarını her oturumda tutarlı biçimde uygulamayabiliyor.',customer:'DevSecOps ekipleri'},en:{idea:'DevSecOps Rule Pack for AI Agents',problem:'AI coding agents may fail to apply project security rules consistently across sessions.',customer:'DevSecOps teams'}},
R016:{tr:{idea:'Kodlama Ajanları için LLM Maliyet Koruması',problem:'Kod ajanları fark edilmeden yüksek API maliyetleri oluşturabiliyor.',customer:'AI kodlama kullanıcıları ve ekipleri'},en:{idea:'LLM Cost Guard for Coding Agents',problem:'Coding agents can quietly generate high API costs.',customer:'AI coding users and teams'}},
R032:{tr:{idea:'AI Üretimi Kod için Güvenlik Kapısı',problem:'AI kodu hızlı üretiyor fakat güvenlik ve kalite kontrolü geride kalabiliyor.',customer:'AI odaklı geliştirme ekipleri'},en:{idea:'AI-Generated Code Security Gate',problem:'AI generates code quickly while security and quality checks can lag behind.',customer:'AI-first development teams'}},
R034:{tr:{idea:'LLM Regresyon CI Sistemi',problem:'Model veya sağlayıcı değişimi uygulama davranışını sessizce bozabiliyor.',customer:'AI ürün ekipleri'},en:{idea:'LLM Regression CI',problem:'A model or provider change can silently break application behavior.',customer:'AI product teams'}},
R001:{tr:{idea:'AI Geliştirme Hafıza Kasası',problem:'AI kodlama oturumlarında kararlar, görev durumu ve bağlam kayboluyor.',customer:'Tek geliştiriciler ve küçük yazılım ekipleri'},en:{idea:'AI Development Memory Vault',problem:'Decisions, task state and context get lost across AI coding sessions.',customer:'Solo developers and small software teams'}},
R033:{tr:{idea:'AI Kod Değişikliği Etki Alanı Analizi',problem:'AI tarafından yapılan değişikliklerin hangi bileşenleri etkilediğini görmek zor.',customer:'Yazılım ekipleri'},en:{idea:'AI Code Change Blast-Radius Analysis',problem:'It is hard to see which components are affected by AI-generated changes.',customer:'Software teams'}},
R007:{tr:{idea:'Özellik İsteği Sinyal / Gürültü Skoru',problem:'Kullanıcı özellik isteklerinde gerçek talep ile gürültüyü ayırmak zor.',customer:'SaaS kurucuları'},en:{idea:'Feature Request Signal / Noise Scorer',problem:'It is difficult to separate real demand from noise in feature requests.',customer:'SaaS founders'}},
R035:{tr:{idea:'AI Model Güvenilirlik Karşılaştırması',problem:'Model seçerken kalite, maliyet ve güvenilirliği aynı görevlerde karşılaştırmak zor.',customer:'AI ekipleri'},en:{idea:'AI Model Reliability Benchmark',problem:'It is difficult to compare quality, cost and reliability on the same tasks.',customer:'AI teams'}},
R030:{tr:{idea:'AI Kodlama Güven Monitörü',problem:'AI kodlama araçlarının ürettiği değişikliklere ne kadar güvenilebileceği ölçülemiyor.',customer:'AI odaklı geliştiriciler'},en:{idea:'AI Coding Trust Monitor',problem:'There is no simple way to quantify trust in changes produced by AI coding tools.',customer:'AI-first developers'}},
R020:{tr:{idea:'PDF Veri Çıkarma Kalite Doğrulayıcısı',problem:'PDF ve tablolardan çıkarılan verinin doğruluğunu hâlâ elle kontrol etmek gerekiyor.',customer:'Operasyon, finans ve analiz ekipleri'},en:{idea:'PDF Extract QA Validator',problem:'Extracted data from PDFs and tables still needs manual accuracy checks.',customer:'Operations, finance and analyst teams'}}
};
let ideas=[],view='live',liveItems=[],liveInfo=null,loadingLive=false,prefs=loadPrefs(),translator=null,translationState='idle';
let translationCache=loadTranslationCache();
const $=s=>document.querySelector(s),t=k=>I18N[prefs.lang][k]??k;
const sc=s=>Math.round(Object.entries(W).reduce((a,[k,w])=>a+(+s[k]||0)*w,0)*200)/10;
function loadPrefs(){try{const p=JSON.parse(localStorage.getItem(PREF)||'{}');return{lang:p.lang==='en'?'en':'tr',theme:['light','dark'].includes(p.theme)?p.theme:(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')}}catch{return{lang:'tr',theme:'light'}}}
function loadTranslationCache(){try{return JSON.parse(localStorage.getItem(TCACHE)||'{}')}catch{return{}}}
function savePrefs(){localStorage.setItem(PREF,JSON.stringify(prefs))}
function saveTranslationCache(){localStorage.setItem(TCACHE,JSON.stringify(translationCache))}
function due(i){if(!i.lastCheck)return true;let d=new Date(i.lastCheck);d.setDate(d.getDate()+(+i.checkInterval||30));return d<=new Date()}
function save(){localStorage.setItem(K,JSON.stringify(ideas));render()}
function localizedIdea(i){const x=SEED_I18N[i.id]?.[prefs.lang];return x?{...i,...x}:i}
function applyPrefs(){document.documentElement.lang=prefs.lang;document.documentElement.dataset.theme=prefs.theme;document.title=t('title');document.querySelector('meta[name="theme-color"]').content=prefs.theme==='dark'?'#171713':'#fff8e8';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$('#langTR')?.classList.toggle('active',prefs.lang==='tr');$('#langEN')?.classList.toggle('active',prefs.lang==='en');$('#themeToggle').textContent=prefs.theme==='dark'?'☀':'☾';$('#themeToggle').setAttribute('aria-label',prefs.theme==='dark'?'Light mode':'Dark mode');localizeStatusSelect();buildScoreControls(true)}
function setLanguage(lang){prefs.lang=lang;savePrefs();applyPrefs();render();if(lang==='tr')ensureLiveTranslations()}
function localizeStatusSelect(){const s=$('#st');if(!s)return;const current=s.value;s.querySelectorAll('option').forEach(o=>o.textContent=I18N[prefs.lang].statuses[o.value]||o.value);s.value=current}
function buildScoreControls(preserve=false){const box=$('#scores');if(!box)return;const existing={};if(preserve)box.querySelectorAll('[data-score]').forEach(x=>existing[x.dataset.score]=x.value);box.innerHTML='';Object.keys(W).forEach(k=>box.insertAdjacentHTML('beforeend',`<label><span>${esc(t(k))}</span><select data-score="${k}">${[1,2,3,4,5].map(n=>`<option${String(existing[k]||3)===String(n)?' selected':''}>${n}</option>`).join('')}</select></label>`));box.querySelectorAll('[data-score]').forEach(x=>x.oninput=calcLive)}
async function init(){ideas=localStorage.getItem(K)?JSON.parse(localStorage.getItem(K)):await fetch('seed.json').then(r=>r.json());applyPrefs();document.querySelector('nav').onclick=e=>{if(e.target.dataset.view){view=e.target.dataset.view;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b===e.target));render();if(view==='live'&&!liveItems.length)loadLive(false)}};['q','cat','status'].forEach(x=>$('#'+x).oninput=render);$('#add').onclick=()=>openIdea();$('#cancel').onclick=()=>$('#dlg').close();$('#form').onsubmit=e=>{e.preventDefault();persist()};$('#refreshLive').onclick=()=>loadLive(true);$('#export').onclick=exportIdeas;$('#import').onchange=importIdeas;$('#langTR').onclick=()=>setLanguage('tr');$('#langEN').onclick=()=>setLanguage('en');$('#themeToggle').onclick=()=>{prefs.theme=prefs.theme==='dark'?'light':'dark';savePrefs();applyPrefs()};render();loadLive(false)}
async function loadLive(force=false){if(loadingLive)return;loadingLive=true;render();try{const res=await fetch('/api/reddit-radar'+(force?'?refresh=1':''),{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();liveItems=Array.isArray(data.items)?data.items:[];liveInfo=data}catch(e){liveInfo={error:e.message};liveItems=[]}finally{loadingLive=false;render();if(prefs.lang==='tr')ensureLiveTranslations()}}
async function ensureLiveTranslations(){if(prefs.lang!=='tr'||!liveItems.length||translationState==='working')return;const pending=liveItems.slice(0,25).filter(i=>!translationCache[i.url]);if(!pending.length)return;if(!('Translator' in window)){translationState='unsupported';render();return}translationState='working';render();try{translator=translator||await Translator.create({sourceLanguage:'en',targetLanguage:'tr'});for(const item of pending){const title=cleanText(item.title),summary=cleanText(item.summary||'');try{translationCache[item.url]={title:await translator.translate(title),summary:summary?await translator.translate(summary.slice(0,1200)):''};saveTranslationCache();render()}catch{translationCache[item.url]={title,summary};}}translationState='done'}catch{translationState='unsupported'}render()}
function exportIdeas(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(ideas,null,2)],{type:'application/json'}));a.download='reddit-opportunity-radar.json';a.click()}
async function importIdeas(e){try{let d=JSON.parse(await e.target.files[0].text());if(!Array.isArray(d))throw 0;ideas=d;save()}catch{alert(t('invalidJson'))}}
function filters(){let c=$('#cat'),s=$('#status'),cv=c.value,sv=s.value;c.innerHTML=`<option value="">${esc(t('all'))}</option>`+[...new Set(ideas.map(i=>i.category).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('');s.innerHTML=`<option value="">${esc(t('all'))}</option>`+[...new Set(ideas.map(i=>i.status).filter(Boolean))].sort().map(x=>`<option value="${esc(x)}">${esc(I18N[prefs.lang].statuses[x]||x)}</option>`).join('');c.value=cv;s.value=sv}
function ideaList(){let q=$('#q').value.toLowerCase(),c=$('#cat').value,s=$('#status').value,a=ideas.filter(i=>{const x=localizedIdea(i);return[x.idea,x.problem,x.customer,x.subreddit].join(' ').toLowerCase().includes(q)&&(!c||i.category===c)&&(!s||i.status===s)});a.sort((a,b)=>sc(b.scores)-sc(a.scores));if(view==='top10')a=a.slice(0,10);if(view==='review')a=a.filter(due);if(view==='dashboard')a=a.slice(0,6);return a}
function liveList(){const q=$('#q').value.toLowerCase();return liveItems.filter(i=>{const tr=prefs.lang==='tr'?translationCache[i.url]:null;return[tr?.title||i.title,tr?.summary||cleanText(i.summary),i.subreddit,i.author].join(' ').toLowerCase().includes(q)}).slice(0,60)}
function render(){filters();let strong=ideas.filter(i=>sc(i.scores)>=85).length;$('#stats').innerHTML=`<div class="stat"><strong>${ideas.length}</strong><span>${esc(t('totalIdeas'))}</span></div><div class="stat"><strong>${strong}</strong><span>${esc(t('strongIdeas'))}</span></div><div class="stat"><strong>${ideas.filter(due).length}</strong><span>${esc(t('reviewWaiting'))}</span></div><div class="stat"><strong>${ideas.filter(i=>i.status==='MVP').length}</strong><span>MVP</span></div><div class="stat"><strong>${liveItems.length}</strong><span>${esc(t('liveSignals'))}</span></div>`;$('#grid').innerHTML='';if(view==='live')renderLive();else renderIdeas()}
function renderLive(){if(loadingLive){$('#liveMeta').textContent=t('scanning');$('#grid').innerHTML=`<div class="empty">${esc(t('updating'))}</div>`;return}if(liveInfo?.error){$('#liveMeta').textContent=t('liveError')+' / '+liveInfo.error;$('#grid').innerHTML=`<div class="empty">${esc(t('sourceOffline'))}</div>`;return}let meta='';if(liveInfo){const tm=new Date(liveInfo.updatedAt).toLocaleString(prefs.lang==='tr'?'tr-TR':'en-US');meta=`${t('lastScan')} ${tm} / ${liveInfo.sources?.length||0} ${t('subreddits')} / ${liveInfo.errors?.length||0} ${t('sourceErrors')}`}else meta=t('preparing');if(prefs.lang==='tr'&&translationState==='working')meta+=' · '+t('translating');if(prefs.lang==='tr'&&translationState==='unsupported')meta+=' · '+t('translationUnavailable');$('#liveMeta').textContent=meta;const a=liveList();if(!a.length){$('#grid').innerHTML=`<div class="empty">${esc(t('noSignal'))}</div>`;return}a.forEach((i,n)=>{const tr=prefs.lang==='tr'?translationCache[i.url]:null,title=tr?.title||cleanText(i.title),summary=(tr?.summary||cleanText(i.summary||t('noDescription'))).slice(0,520),score=Number(i.signalScore)||0;$('#grid').insertAdjacentHTML('beforeend',`<article class="signal-row"><div class="rank">${String(n+1).padStart(2,'0')}</div><div class="signal-main"><div class="eyebrow">${esc(i.subreddit)} / ${esc(i.author||t('anonymous'))} / ${formatDate(i.published)}${tr?` / ${esc(t('translated'))}`:''}</div><h2>${esc(title)}</h2><p class="problem">${esc(summary)}</p><div class="signal-actions"><a href="${safeUrl(i.url)}" target="_blank" rel="noopener noreferrer">${esc(t('redditSource'))}</a><button data-promote="${n}">${esc(t('promote'))}</button></div></div><div class="scorebox ${score>=70?'high':''}"><strong>${score}</strong><span>${esc(t('signal'))}</span></div></article>`)});document.querySelectorAll('[data-promote]').forEach(b=>b.onclick=()=>promote(a[Number(b.dataset.promote)]))}
function renderIdeas(){$('#liveMeta').textContent='';const a=ideaList();if(!a.length){$('#grid').innerHTML=`<div class="empty">${esc(t('noIdeas'))}</div>`;return}a.forEach((raw,n)=>{const i=localizedIdea(raw),score=sc(raw.scores),meta=[raw.category,raw.subreddit,i.customer].filter(Boolean).join(' / '),status=I18N[prefs.lang].statuses[raw.status]||raw.status;$('#grid').insertAdjacentHTML('beforeend',`<article class="signal-row"><div class="rank">${String(n+1).padStart(2,'0')}</div><div class="signal-main"><div class="eyebrow">${esc(meta||t('personalIdea'))}</div><h2>${esc(i.idea)}</h2><p class="problem">${esc(i.problem)}</p><div class="statusline"><span>${esc(status)}</span>${due(raw)?`<span class="due">${esc(t('reviewDue'))}</span>`:''}</div><div class="signal-actions">${raw.sourceUrl?`<a href="${safeUrl(raw.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(t('source'))}</a>`:''}<button data-id="${raw.id}">${esc(t('edit'))}</button></div></div><div class="scorebox ${score>=85?'high':''}"><strong>${score}</strong><span>${esc(t('opportunity'))}</span></div></article>`)});document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openIdea(ideas.find(i=>i.id===b.dataset.id)))}
function promote(i){const tr=prefs.lang==='tr'?translationCache[i.url]:null;openIdea({idea:tr?.title||cleanText(i.title),problem:tr?.summary||cleanText(i.summary)||cleanText(i.title),subreddit:i.subreddit,sourceUrl:i.url,status:'İncele',checkInterval:14,scores:{pain:4,willingness:3,frequency:3,distribution:3,mvp:3,gap:3,fit:3}})}
function cleanText(x=''){const doc=new DOMParser().parseFromString(String(x),'text/html');return(doc.body.textContent||'').replace(/\s+/g,' ').trim()}
function esc(x=''){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function safeUrl(u=''){try{const x=new URL(u);return['https:','http:'].includes(x.protocol)?x.href:'#'}catch{return'#'}}
function formatDate(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString(prefs.lang==='tr'?'tr-TR':'en-US',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function openIdea(i={}){const loc=i.id?localizedIdea(i):i;for(let[id,k]of[['id','id'],['name','idea'],['problem','problem'],['customer','customer'],['category','category'],['subreddit','subreddit'],['url','sourceUrl'],['st','status'],['interval','checkInterval']])$('#'+id).value=loc[k]||($('#'+id).type==='number'?30:'');document.querySelectorAll('[data-score]').forEach(x=>x.value=i.scores?.[x.dataset.score]||3);localizeStatusSelect();calcLive();$('#dlg').showModal()}
function calcLive(){let s={};document.querySelectorAll('[data-score]').forEach(x=>s[x.dataset.score]=+x.value);$('#live').textContent=sc(s)}
function persist(){let id=$('#id').value||'R'+Date.now(),scores={};document.querySelectorAll('[data-score]').forEach(x=>scores[x.dataset.score]=+x.value);let o={id,idea:$('#name').value.trim(),problem:$('#problem').value.trim(),customer:$('#customer').value.trim(),category:$('#category').value.trim(),subreddit:$('#subreddit').value.trim(),sourceUrl:$('#url').value.trim(),status:$('#st').value,checkInterval:+$('#interval').value||30,lastCheck:new Date().toISOString().slice(0,10),scores};let ix=ideas.findIndex(i=>i.id===id);ix<0?ideas.unshift(o):ideas[ix]={...ideas[ix],...o};save();$('#dlg').close()}
init();
