const K='redditRadar.v1',W={pain:.25,willingness:.20,frequency:.15,distribution:.10,mvp:.10,gap:.10,fit:.10},L={pain:'Acı',willingness:'Ödeme isteği',frequency:'Tekrar',distribution:'Dağıtım',mvp:'MVP',gap:'Rekabet boşluğu',fit:'Uyum'};
let ideas=[],view='live',liveItems=[],liveInfo=null,loadingLive=false;
const $=s=>document.querySelector(s),sc=s=>Math.round(Object.entries(W).reduce((a,[k,w])=>a+(+s[k]||0)*w,0)*200)/10;
function due(i){if(!i.lastCheck)return true;let d=new Date(i.lastCheck);d.setDate(d.getDate()+(+i.checkInterval||30));return d<=new Date()}
function save(){localStorage.setItem(K,JSON.stringify(ideas));render()}
async function init(){ideas=localStorage.getItem(K)?JSON.parse(localStorage.getItem(K)):await fetch('seed.json').then(r=>r.json());Object.keys(W).forEach(k=>{$('#scores').insertAdjacentHTML('beforeend',`<label>${L[k]}<select data-score="${k}">${[1,2,3,4,5].map(n=>`<option>${n}</option>`).join('')}</select></label>`)});document.querySelectorAll('[data-score]').forEach(x=>x.oninput=calcLive);document.querySelector('nav').onclick=e=>{if(e.target.dataset.view){view=e.target.dataset.view;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b===e.target));render();if(view==='live'&&!liveItems.length)loadLive(false)}};['q','cat','status'].forEach(x=>$('#'+x).oninput=render);$('#add').onclick=()=>openIdea();$('#cancel').onclick=()=>$('#dlg').close();$('#form').onsubmit=e=>{e.preventDefault();persist()};$('#refreshLive').onclick=()=>loadLive(true);$('#export').onclick=exportIdeas;$('#import').onchange=importIdeas;render();loadLive(false)}
async function loadLive(force=false){if(loadingLive)return;loadingLive=true;render();try{const res=await fetch('/api/reddit-radar'+(force?'?refresh=1':''),{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();liveItems=Array.isArray(data.items)?data.items:[];liveInfo=data}catch(e){liveInfo={error:e.message};liveItems=[]}finally{loadingLive=false;render()}}
function exportIdeas(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(ideas,null,2)],{type:'application/json'}));a.download='reddit-firsat-radari.json';a.click()}
async function importIdeas(e){try{let d=JSON.parse(await e.target.files[0].text());if(!Array.isArray(d))throw 0;ideas=d;save()}catch{alert('Geçerli JSON seç.')}}
function filters(){let c=$('#cat'),s=$('#status'),cv=c.value,sv=s.value;c.innerHTML='<option value="">Tüm kategoriler</option>'+[...new Set(ideas.map(i=>i.category).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('');s.innerHTML='<option value="">Tüm durumlar</option>'+[...new Set(ideas.map(i=>i.status).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('');c.value=cv;s.value=sv}
function ideaList(){let q=$('#q').value.toLowerCase(),c=$('#cat').value,s=$('#status').value,a=ideas.filter(i=>[i.idea,i.problem,i.customer,i.subreddit].join(' ').toLowerCase().includes(q)&&(!c||i.category===c)&&(!s||i.status===s));a.sort((a,b)=>sc(b.scores)-sc(a.scores));if(view==='top10')a=a.slice(0,10);if(view==='review')a=a.filter(due);if(view==='dashboard')a=a.slice(0,6);return a}
function liveList(){const q=$('#q').value.toLowerCase();return liveItems.filter(i=>[i.title,i.summary,i.subreddit,i.author].join(' ').toLowerCase().includes(q)).slice(0,60)}
function render(){filters();let strong=ideas.filter(i=>sc(i.scores)>=85).length;$('#stats').innerHTML=`<div class="stat"><strong>${ideas.length}</strong><span>Toplam fikir</span></div><div class="stat"><strong>${strong}</strong><span>85+ güçlü fırsat</span></div><div class="stat"><strong>${ideas.filter(due).length}</strong><span>Kontrol zamanı</span></div><div class="stat"><strong>${ideas.filter(i=>i.status==='MVP').length}</strong><span>MVP aşamasında</span></div><div class="stat"><strong>${liveItems.length}</strong><span>Canlı sinyal</span></div>`;$('#grid').innerHTML='';if(view==='live')renderLive();else renderIdeas()}
function renderLive(){if(loadingLive){$('#liveMeta').textContent='Reddit akışı güncelleniyor…';$('#grid').innerHTML='<div class="empty">Kaynaklar taranıyor.</div>';return}if(liveInfo?.error){$('#liveMeta').textContent='Canlı veri alınamadı: '+liveInfo.error;$('#grid').innerHTML='<div class="empty">Netlify Functions deploy edildikten sonra canlı radar burada çalışacak.</div>';return}if(liveInfo){const t=new Date(liveInfo.updatedAt).toLocaleString('tr-TR');$('#liveMeta').textContent=`Son tarama: ${t} · ${liveInfo.sources?.length||0} subreddit · ${liveInfo.errors?.length||0} kaynak hatası`;}else $('#liveMeta').textContent='Canlı Reddit sinyalleri hazırlanıyor…';const a=liveList();if(!a.length){$('#grid').innerHTML='<div class="empty">Henüz canlı sinyal yok.</div>';return}a.forEach((i,n)=>{$('#grid').insertAdjacentHTML('beforeend',`<article class="card live-card"><div class="cardtop"><span>#${n+1} · ${esc(i.subreddit)}</span><span class="pill ${i.signalScore>=70?'signal-high':i.signalScore>=50?'signal-mid':''}">${i.signalScore}</span></div><h3>${esc(i.title)}</h3><p class="problem">${esc(i.summary||'Açıklama yok').slice(0,420)}</p><div class="meta">${esc(i.author||'')} · ${formatDate(i.published)}</div><div class="cardfoot"><a class="source-link" href="${safeUrl(i.url)}" target="_blank" rel="noopener noreferrer">Reddit'te aç</a><button data-promote="${n}">Fikre dönüştür</button></div></article>`)});document.querySelectorAll('[data-promote]').forEach((b,idx)=>b.onclick=()=>promote(a[Number(b.dataset.promote)]||a[idx]))}
function renderIdeas(){$('#liveMeta').textContent='';const a=ideaList();if(!a.length){$('#grid').innerHTML='<div class="empty">Bu görünümde fikir bulunamadı.</div>';return}a.forEach((i,n)=>{$('#grid').insertAdjacentHTML('beforeend',`<article class="card"><div class="cardtop"><span>#${n+1}</span><span class="pill">${sc(i.scores)}</span></div><h3>${esc(i.idea)}</h3><p class="problem">${esc(i.problem)}</p><div class="meta">${esc([i.category,i.subreddit,i.customer].filter(Boolean).join(' · '))}</div><div class="cardfoot"><span class="badge ${due(i)?'due':''}">${esc(i.status)}${due(i)?' · kontrol zamanı':''}</span><button data-id="${i.id}">Aç / düzenle</button></div></article>`)});document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openIdea(ideas.find(i=>i.id===b.dataset.id)))}
function promote(i){openIdea({idea:i.title,problem:i.summary||i.title,subreddit:i.subreddit,sourceUrl:i.url,status:'İncele',checkInterval:14,scores:{pain:4,willingness:3,frequency:3,distribution:3,mvp:3,gap:3,fit:3}})}
function esc(x=''){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(u=''){try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)?esc(x.href):'#'}catch{return '#'}}
function formatDate(v){if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString('tr-TR')}
function openIdea(i={}){for(let [id,k] of [['id','id'],['name','idea'],['problem','problem'],['customer','customer'],['category','category'],['subreddit','subreddit'],['url','sourceUrl'],['st','status'],['interval','checkInterval']])$('#'+id).value=i[k]||($('#'+id).type==='number'?30:'');document.querySelectorAll('[data-score]').forEach(x=>x.value=i.scores?.[x.dataset.score]||3);calcLive();$('#dlg').showModal()}
function calcLive(){let s={};document.querySelectorAll('[data-score]').forEach(x=>s[x.dataset.score]=+x.value);$('#live').textContent=sc(s)}
function persist(){let id=$('#id').value||'R'+Date.now(),scores={};document.querySelectorAll('[data-score]').forEach(x=>scores[x.dataset.score]=+x.value);let o={id,idea:$('#name').value.trim(),problem:$('#problem').value.trim(),customer:$('#customer').value.trim(),category:$('#category').value.trim(),subreddit:$('#subreddit').value.trim(),sourceUrl:$('#url').value.trim(),status:$('#st').value,checkInterval:+$('#interval').value||30,lastCheck:new Date().toISOString().slice(0,10),scores};let ix=ideas.findIndex(i=>i.id===id);ix<0?ideas.unshift(o):ideas[ix]={...ideas[ix],...o};save();$('#dlg').close()}
init();
